<?php

namespace Tests\Feature\Policies;

use App\Constants\Admins;
use App\Constants\Permissions;
use App\Models\Admin\Admin;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Database\Seeders\PermissionSeeder;
use Database\Seeders\RoleSeeder;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class RolePolicyTest extends TestCase
{
    use RefreshDatabase;

    private $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed([
            PermissionSeeder::class,
            RoleSeeder::class,
        ]);
        $this->admin = factory(Admin::class)->create();
    }

    /**
     * A admin without permission to view roles will be unauthorized.
     *
     * @return void
     */
    public function testIndexNotAuthorized(): void
    {
        $response = $this->actingAs($this->admin, Admins::GUARDED)->get(route('roles.index'));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotUpdateRoles(): void
    {
        $role = factory(Role::class)->create();

        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->put(route('roles.update', $role->id));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotDeleteRoles(): void
    {
        $role = factory(Role::class)->create();
        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->delete(route('roles.update', $role->id));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotCreateRoles(): void
    {
        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->post(route('roles.store'), [
                'name' => 'test role',
            ]);

        $response->assertStatus(403);
    }

    public function testAllRoleRoutesWithPermissions(): void
    {
        $id = Role::all()->random()->id;
        $role = factory(Role::class)->create();

        $role->syncPermissions([
            Permissions::VIEW_ROLES,
            Permissions::DELETE_ROLES,
            Permissions::EDIT_ROLES,
            Permissions::CREATE_ROLES,
        ]);

        $this->admin->assignRole($role->name);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->get(route('roles.index'))->assertStatus(200);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->put(route('roles.update', $id))->assertStatus(302);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->delete(route('roles.destroy', $id))->assertStatus(302);

        $this->actingAs($this->admin, Admins::GUARDED)->post(route('roles.store', $id), [
            'name' => 'test role',
        ])->assertStatus(302);
    }
}
