<?php

namespace Tests\Feature\Policies;

use App\Constants\Admins;
use App\Constants\Permissions;
use App\Models\Admin\Admin;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Database\Seeders\PermissionSeeder;
use Database\Seeders\RoleSeeder;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class UserPolicyTest extends TestCase
{
    use RefreshDatabase;

    private $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed([
            PermissionSeeder::class,
            RoleSeeder::class,
        ]);
        $this->admin = factory(Admin::class)->create();
    }

    public function testIndexNotAuthorized(): void
    {
        $response = $this->actingAs($this->admin, Admins::GUARDED)->get(route('users.index'));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotUpdateUsers(): void
    {
        $user = factory(User::class)->create();
        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->put(route('users.update', $user->id));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotViewAnUser(): void
    {
        $user = factory(User::class)->create();
        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->get(route('users.show', $user->id));

        $response->assertStatus(403);
    }

    public function testAdminWithoutPermissionCannotDeleteUsers(): void
    {
        $user = factory(User::class)->create();
        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->delete(route('users.destroy', $user->id));

        $response->assertStatus(403);
    }

    public function testAllUsersRoutesWithPermissions(): void
    {
        $user = factory(User::class)->create();
        $role = factory(Role::class)->create();

        $role->syncPermissions([
            Permissions::VIEW_USERS,
            Permissions::EDIT_USERS,
            Permissions::DELETE_USERS,
        ]);

        $this->admin->assignRole($role->name);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->get(route('users.index'))->assertStatus(200);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->put(route('users.update', $user->id))->assertStatus(302);

        $this->actingAs($this->admin, Admins::GUARDED)
            ->delete(route('users.destroy', $user->id))->assertStatus(302);
    }
}
